---
- name: Pull latest phpmyadmin image
  containers.podman.podman_image:
    name: phpmyadmin:latest

- name: Start phpmyadmin container
  containers.podman.podman_container:
    name: phpmyadmin
    image: phpmyadmin:latest
    state: started
    env:
       PMA_HOST: "{{ VAR_PHPMYADMIN_URL }}"
    ports:
      - 8082:80
  register: container

- name: Create new systemd file
  shell: podman generate systemd --name traefik > /etc/systemd/system/container-traefik.service
  when: container.changed

- name: restart container with systemd
  systemd:
    state: restarted
    daemon_reload: yes
    name: container-traefik
  when: container.changed

